version: 2.1
commands:
  make:
    description: "Make in a given directory"
    parameters:
      dir:
        type: string
        default: "."
    steps:
      - checkout
      - run: cd << parameters.dir >> && make

  valgrind:
    description: "run valgrind on an binary in a given directory"
    parameters:
      dir:
        type: string
        default: "."
      script-name:
        type: string
        default: "."
    steps:
      - checkout
      - run: cd << parameters.dir >> && make && valgrind --leak-check=full << parameters.script-name >>