version: 2
jobs:
  ex1-sort-simple-build:
    working_directory: ~/project/exercise1/sort_simple
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - run:
          name: Make sort_simple
          command: cd exercise1/sort_simple && make

  ex1-sort-simple-valgrind:
    working_directory: ~/project/exercise1/sort_simple
    docker:
      - image: mooreryan/valgrind
    steps:
      - checkout
      - run:
          name: valgrind sort_simple
          command: cd exercise1/sort_simple && make && valgrind --leak-check=full ./test.sh

workflows:
    version: 2
    build-test:
      jobs:
        - ex1-sort-simple-build
        - ex1-sort-simple-valgrind