version: 2.1
commands:
  make:
    description: "Make in a given directory"
    parameters:
      dir:
        type: string
        default: "."
    steps:
      - checkout
      - run: cd << parameters.dir >> && make

  valgrind:
    description: "run valgrind on an binary in a given directory"
    parameters:
      dir:
        type: string
        default: "."
      script-name:
        type: string
        default: "."
    steps:
      - checkout
      - run: cd << parameters.dir >> && make && valgrind --leak-check=full << parameters.script-name >>

jobs:
  ex1-sort-simple-build:
    working_directory: ~/project/exercise1/sort_simple
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - make:
          dir: exercise1/sort_simple

  ex1-sort-simple-valgrind:
    working_directory: ~/project/exercise1/sort_simple
    docker:
      - image: mooreryan/valgrind
    steps:
    - checkout
    - valgrind:
        dir: exercise1/sort_simple
        script-name: sort
  
workflows:
    version: 2
    build-test:
      jobs:
        - ex1-sort-simple-build
        - ex1-sort-simple-valgrind