version: 2.1
commands:
  make:
    description: "Make in a given directory"
    parameters:
      dir:
        type: string
        default: "."
    steps:
      - checkout
      - run: cd << parameters.dir >> && make

  valgrind:
    description: "run valgrind on an binary in a given directory"
    parameters:
      dir:
        type: string
        default: "."
      script-name:
        type: string
        default: "."
    steps:
      - checkout
      - run: cd << parameters.dir >> && make && valgrind --leak-check=full << parameters.script-name >>

  test:
    description: "run test script in a given directory"
    parameters:
      dir:
        type: string
        default: "."
      script-name:
        type: string
        default: "."
    steps:
      - checkout
      - run: cd << parameters.dir >> && make && << parameters.script-name >>

jobs:
  ex1-sort-simple-build:
    working_directory: ~/project/exercise1/sort_simple
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - make:
          dir: exercise1/sort_simple

  ex1-sort-simple-valgrind:
    working_directory: ~/project/exercise1/sort_simple
    docker:
      - image: mooreryan/valgrind
    steps:
    - checkout
    - valgrind:
        dir: exercise1/sort_simple
        script-name: sort

  ex1-sort-simple-test:
    working_directory: ~/project/exercise1/sort_simple
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - valgrind:
          dir: exercise1/sort_simple
          script-name: ./test.sh

  ex1-sort-advanced-build:
    working_directory: ~/project/exercise1/sort_advanced
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - make:
          dir: exercise1/sort_advanced

  ex1-sort-advanced-valgrind:
    working_directory: ~/project/exercise1/sort_advanced
    docker:
      - image: mooreryan/valgrind
    steps:
      - checkout
      - valgrind:
          dir: exercise1/sort_advanced
          script-name: sort

  ex1-sort-advanced-test:
    working_directory: ~/project/exercise1/sort_advanced
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - valgrind:
          dir: exercise1/sort_advanced
          script-name: ./test.sh

  ex1-linked-list-build:
    working_directory: ~/project/exercise1/sort_advanced
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - make:
          dir: exercise1/sort_advanced

  ex1-linked-list-valgrind:
    working_directory: ~/project/exercise1/linked_list
    docker:
      - image: mooreryan/valgrind
    steps:
      - checkout
      - valgrind:
          dir: exercise1/linked_list
          script-name: test_list

  ex1-linked-list-test:
    working_directory: ~/project/exercise1/linked_list
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - valgrind:
          dir: exercise1/linked_lists
          script-name: ./test.sh
  
workflows:
    version: 2
    sort-simple:
      jobs:
        - ex1-sort-simple-build
        - ex1-sort-simple-valgrind
        - ex1-sort-simple-test
    sort-advanced:
      jobs:
        - ex1-sort-advanced-build
        - ex1-sort-advanced-valgrind
        - ex1-sort-advanced-test
    linked-list:
      jobs:
        - ex1-linked-list-build
        - ex1-linked-list-valgrind
        - ex1-linked-list-test